FROM python:3.8-alpine

COPY ./requirements.txt /authorsapi/requirements.txt
COPY ./authors.py /authorsapi/authors.py
COPY ./db.json /authorsapi/db.json

WORKDIR /authorsapi

RUN pip install -r requirements.txt

# EXPOSE 8000

CMD [ "uvicorn", "authors:app", "--host", "0.0.0.0", "--port", "8000" ]